/**
 * LLM Asserter - Generates human-readable assertions from eval results
 *
 * This module uses an LLM to analyze deterministic eval results and generate:
 * - Human-readable assertions (explaining why something passed/failed)
 * - Improvement suggestions (how to fix issues)
 *
 * IMPORTANT: This module does NOT participate in pass/fail judgment.
 * The deterministic Evaluator (src/evaluator/) is responsible for that.
 * This module only provides human-readable explanations and suggestions.
 */

import Anthropic from '@anthropic-ai/sdk';
import pino from 'pino';
import type { EvalResult } from './schemas/eval-result.js';
import type { RunRecord } from './schemas/run-record.js';

const logger = pino({
  transport: {
    target: 'pino-pretty',
    options: { colorize: true },
  },
});

// ============================================
// Types
// ============================================

/**
 * A human-readable assertion generated by LLM
 */
export interface Assertion {
  id: string;
  type: 'pass' | 'fail' | 'warning';
  category: 'correctness' | 'coverage' | 'efficiency' | 'behavior' | 'error';
  message: string;
  evidence_refs: string[]; // References to evidence (e.g., "output.text")
  confidence: number; // 0-1
  patch_suggestion?: string; // Suggested fix for failures
}

/**
 * A suggestion for improvement
 */
export interface Suggestion {
  type: 'prompt_change' | 'config_change' | 'workflow_fix' | 'other';
  description: string;
  priority: 'high' | 'medium' | 'low';
  affected_rules?: string[]; // Which rules this suggestion addresses
}

/**
 * Output from LLM Asserter
 */
export interface AssertionOutput {
  assertions: Assertion[];
  suggestions: Suggestion[];
  summary: string;
  generated_at: string;
}

/**
 * Status of assertion generation
 */
export type AssertionStatus = 'success' | 'skipped' | 'unavailable' | 'error';

/**
 * Result wrapper with explicit status
 *
 * This allows callers to distinguish between:
 * - success: Assertions generated successfully
 * - skipped: No violations to explain (everything passed)
 * - unavailable: No API key configured
 * - error: LLM call failed (includes error message for retry/debugging)
 */
export interface GenerateAssertionsResult {
  status: AssertionStatus;
  output?: AssertionOutput;
  reason?: string; // Human-readable reason for non-success status
  error?: string; // Error message (only for status: 'error')
}

/**
 * Input for LLM Asserter
 */
export interface AssertionInput {
  evalResult: EvalResult; // Deterministic evaluation result
  runRecord: RunRecord; // Full execution record
  context?: {
    leaf?: { id: string; type: string; content?: string };
    inputs?: Record<string, unknown>;
  };
}

// ============================================
// LLM Asserter Class
// ============================================

export class LLMAsserter {
  private client: Anthropic | null = null;
  private model = 'claude-sonnet-4-20250514';
  private readonly hasApiKey: boolean;

  constructor() {
    const apiKey = process.env.ANTHROPIC_API_KEY;
    this.hasApiKey = !!apiKey;

    if (apiKey) {
      this.client = new Anthropic({ apiKey });
      logger.info('LLM Asserter initialized with Anthropic API');
    } else {
      logger.info('ANTHROPIC_API_KEY not set, LLM assertions disabled');
    }
  }

  /**
   * Check if LLM assertions are available
   */
  isAvailable(): boolean {
    return this.hasApiKey && this.client !== null;
  }

  /**
   * Generate assertions from eval result
   *
   * Returns GenerateAssertionsResult with explicit status:
   * - success: Assertions generated successfully
   * - skipped: No violations to explain (everything passed)
   * - unavailable: No API key configured
   * - error: LLM call failed (with error message for debugging/retry)
   */
  async generateAssertions(input: AssertionInput): Promise<GenerateAssertionsResult> {
    // No API key → unavailable (caller can decide how to handle)
    if (!this.client) {
      logger.warn({ run_id: input.evalResult.run_id }, 'LLM assertions unavailable: no API key');
      return {
        status: 'unavailable',
        reason: 'ANTHROPIC_API_KEY not configured. LLM assertions require an API key.',
      };
    }

    // No violations → skipped (this is expected behavior for passing runs)
    if (input.evalResult.violations.length === 0 && input.evalResult.passed) {
      logger.debug({ run_id: input.evalResult.run_id }, 'LLM assertions skipped: no violations');
      return {
        status: 'skipped',
        reason: 'All checks passed. No violations to explain.',
      };
    }

    const startTime = Date.now();

    try {
      // Build prompt for LLM
      const prompt = this.buildPrompt(input);

      // Call LLM
      const response = await this.client.messages.create({
        model: this.model,
        max_tokens: 2000,
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      // Parse LLM response
      const content = response.content[0];
      if (content.type !== 'text') {
        throw new Error('Unexpected response type from LLM');
      }

      const output = this.parseLLMResponse(content.text);

      const latencyMs = Date.now() - startTime;
      logger.info(
        {
          run_id: input.evalResult.run_id,
          latency_ms: latencyMs,
          assertions_count: output.assertions.length,
          suggestions_count: output.suggestions.length,
        },
        'LLM assertions generated'
      );

      return {
        status: 'success',
        output,
      };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      logger.error(
        { run_id: input.evalResult.run_id, error: errorMsg },
        'LLM assertion generation failed'
      );

      // Return error status with message (caller can retry or show to user)
      return {
        status: 'error',
        reason: 'LLM assertion generation failed. This may be a temporary issue.',
        error: errorMsg,
      };
    }
  }

  /**
   * Build prompt for LLM
   */
  private buildPrompt(input: AssertionInput): string {
    const { evalResult, runRecord, context } = input;

    // Format violations for the prompt
    const violationsText = evalResult.violations
      .map(
        (v, i) =>
          `${i + 1}. [${v.severity}] ${v.message}${v.step_id ? ` (step: ${v.step_id})` : ''}`
      )
      .join('\n');

    // Format check results
    const checksText = evalResult.checks
      .map((c) => `- ${c.rule_id}: ${c.passed ? '✓' : '✗'} ${c.message}`)
      .join('\n');

    return `You are an AI agent evaluator. A deterministic evaluation has been completed, and you need to generate human-readable assertions and improvement suggestions.

## Evaluation Summary
- Run ID: ${evalResult.run_id}
- Passed: ${evalResult.passed ? 'YES' : 'NO'}
- Score: ${(evalResult.score * 100).toFixed(1)}%
- Rules Version: ${evalResult.rules_version}

## Check Results
${checksText}

## Violations (${evalResult.violations.length})
${violationsText || 'None'}

## Run Record
- Status: ${runRecord.status}
- Steps: ${runRecord.steps.length}
- Total Latency: ${runRecord.timing.total_ms || 'unknown'}ms
${runRecord.error ? `- Error: ${runRecord.error.message}` : ''}

## Output (truncated)
${JSON.stringify(runRecord.output, null, 2)?.slice(0, 1000) || 'No output'}

${context?.inputs ? `## Inputs\n${JSON.stringify(context.inputs, null, 2)?.slice(0, 500)}` : ''}

## Task
Based on the evaluation results above, generate ONE concise overall assessment:

1. **Summary**: A brief summary of what happened (1-2 sentences)
2. **Improvement**: ONE key improvement suggestion that would have the biggest impact

Keep it concise and actionable. Focus on the most important issue.

Respond in JSON:
{
  "assertions": [
    {
      "type": "pass" or "fail" or "warning",
      "category": "correctness" or "efficiency" or "behavior" or "error",
      "message": "One sentence overall assessment",
      "evidence_refs": ["key evidence path"],
      "confidence": 0.0-1.0,
      "patch_suggestion": "One key improvement suggestion (if failed)"
    }
  ],
  "suggestions": [],
  "summary": "Brief 1-2 sentence summary"
}`;
  }

  /**
   * Parse LLM response into structured result
   */
  private parseLLMResponse(text: string): AssertionOutput {
    try {
      // Extract JSON from response (handle markdown code blocks)
      let jsonStr = text;
      const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        jsonStr = jsonMatch[1];
      }

      const parsed = JSON.parse(jsonStr);

      return {
        assertions: parsed.assertions || [],
        suggestions: parsed.suggestions || [],
        summary: parsed.summary || '',
        generated_at: new Date().toISOString(),
      };
    } catch (error) {
      logger.error({ error: String(error) }, 'Failed to parse LLM response');

      // Return minimal result on parse failure
      return {
        assertions: [],
        suggestions: [],
        summary: 'Failed to parse LLM response',
        generated_at: new Date().toISOString(),
      };
    }
  }
}

// Singleton instance
export const llmAsserter = new LLMAsserter();

// ============================================
// Legacy exports for backward compatibility
// ============================================

/** @deprecated Use AssertionInput instead */
export interface GenerateAssertionsInput {
  run_id: string;
  leaf?: { id: string; type: 'deploy' | 'eval'; content?: string };
  inputs?: Record<string, unknown>;
  run_report: { output?: Record<string, unknown>; meta?: { latency_ms?: number; tokens?: number } };
  evidence_pack: {
    n8n_output?: Record<string, unknown>;
    n8n_meta?: { latency_ms?: number; tokens?: number };
    error?: string | null;
  };
  eval_rules?: {
    expected_output?: string;
    must_contain?: string[];
    must_not_contain?: string[];
    custom_checks?: string[];
  };
}

/** @deprecated Use EvalResult.score instead */
export interface EvalMetrics {
  correctness?: number;
  coverage?: number;
  efficiency?: number;
}

/** @deprecated Use AssertionOutput instead */
export interface AssertionResult {
  run_id: string;
  assertions: Assertion[];
  metrics: EvalMetrics;
  summary: string;
  generated_at: string;
}
