// @t3x-dev/yschema — P0 schema contract validation

export type {
  CompiledYSchemaComposition,
  CompileYSchemaCompositionInput,
  YSchemaArtifactFamily,
  YSchemaArtifactReference,
  YSchemaArtifactSource,
  YSchemaArtifactStatus,
  YSchemaCompositionDraft,
  YSchemaCompositionIssue,
  YSchemaCompositionIssueCode,
  YSchemaCompositionModuleReference,
  YSchemaCompositionPathOrigin,
  YSchemaCompositionRenderEntry,
  YSchemaCompositionVerificationReport,
  YSchemaCoreArtifact,
  YSchemaModuleKind,
  YSchemaModuleManifest,
} from './composition';
export {
  builtInEsphomeDeviceCoreArtifact,
  builtInEsphomeDeviceModules,
  builtInPrdCoreArtifact,
  builtInPrdModules,
  builtInPromptCoreArtifact,
  builtInPromptModules,
  builtInSkillCoreArtifact,
  builtInSkillModules,
  builtInYSchemaCores,
  builtInYSchemaModules,
  canonicalizeCompositionValue,
  compileYSchemaComposition,
  defaultEsphomeDeviceCompositionModuleOrder,
  defaultPrdCompositionModuleOrder,
  defaultPromptCompositionModuleOrder,
  defaultSkillCompositionModuleOrder,
  sha256CompositionValue,
} from './composition';
export type {
  CompiledYSchemaCompositionV2,
  CompileYSchemaCompositionV2Input,
  YSchemaCapabilityBindingV2,
  YSchemaCompositionDraftV2,
  YSchemaCompositionIssueCodeV2,
  YSchemaCompositionIssueV2,
  YSchemaCompositionModuleReferenceV2,
  YSchemaCompositionOriginV2,
  YSchemaCompositionPolicyV2,
  YSchemaCompositionRenderEntryV2,
  YSchemaModuleArtifactV2,
  YSchemaModuleImportV2,
  YSchemaModuleSuggestionV2,
} from './composition-v2';
export { compileYSchemaCompositionV2 } from './composition-v2';
export type {
  ContentKind,
  DiffValidationResultsInput,
  FixProposal,
  NodeSchema,
  PromptContract,
  PromptNodeContract,
  PromptRelationTypeContract,
  PromptSlotContract,
  ProvenanceIndex,
  ProvenanceRef,
  RelateYOp,
  RelationEndpointPattern,
  RelationTypeSchema,
  RenderComposedYSchemaMarkdownInput,
  RenderYSchemaMarkdownInput,
  ReservedRuleSchema,
  SlotSchema,
  SlotType,
  UnrelateYOp,
  ValidationError,
  ValidationErrorCode,
  ValidationGap,
  ValidationGapCode,
  ValidationInput,
  ValidationLocation,
  ValidationResult,
  YOpsHint,
  YSchema,
  YSchemaFixOp,
  YSchemaKey,
  YSchemaPath,
  YSchemaRelation,
  YSchemaValidationDelta,
} from './p0';
export {
  diffValidationResults,
  generatePromptContract,
  normalizeYSchemaObject,
  parseYSchema,
  renderComposedYSchemaMarkdown,
  renderYSchemaMarkdown,
  t3xPrdP0Fixtures,
  t3xPromptP0Fixtures,
  t3xSkillP0Fixtures,
  validateTree,
} from './p0';
