// @t3x-dev/yschema — P0 schema contract validation

export type {
  ContentKind,
  FixProposal,
  NodeSchema,
  PromptContract,
  PromptNodeContract,
  PromptRelationTypeContract,
  PromptSlotContract,
  ProvenanceIndex,
  ProvenanceRef,
  RelateYOp,
  RelationEndpointPattern,
  RelationTypeSchema,
  ReservedRuleSchema,
  SlotSchema,
  SlotType,
  UnrelateYOp,
  ValidationError,
  ValidationErrorCode,
  ValidationGap,
  ValidationGapCode,
  ValidationInput,
  ValidationLocation,
  ValidationResult,
  YOpsHint,
  YSchema,
  YSchemaFixOp,
  YSchemaKey,
  YSchemaPath,
  YSchemaRelation,
} from './p0';
export {
  generatePromptContract,
  normalizeYSchemaObject,
  parseYSchema,
  t3xPrdP0Fixtures,
  validateTree,
} from './p0';
