/**
 * Merge Release Note Generator — Pure Function
 *
 * Transforms merge result + resolutions into a structured release note
 * with human-readable sections (added/updated/removed/conflicts).
 */

import type { Merge2WayResult, MergeSimilarPair } from '@t3x-dev/core';
import type { MergeSummary } from '@/lib/mergeSummary';
import type { ExtendedResolutionData } from '@/store/mergeWorkspaceStore';

// ============================================================================
// Types
// ============================================================================

export interface ReleaseNoteSection {
  heading: string;
  items: string[];
}

export interface MergeReleaseNote {
  title: string;
  timestamp: string;
  sourceBranch: string;
  targetBranch: string;
  summary: string;
  sections: ReleaseNoteSection[];
}

// ============================================================================
// Main Function
// ============================================================================

/**
 * Generate a structured release note from merge data.
 *
 * @param prepared - The Merge2WayResult from prepareMerge()
 * @param summary - Pre-computed merge summary
 * @param sourceBranch - Source branch name
 * @param targetBranch - Target branch name
 * @param extendedResolutions - Optional extended resolutions (e.g. 'both')
 */
export function generateMergeReleaseNote(
  prepared: Merge2WayResult,
  summary: MergeSummary,
  sourceBranch: string,
  targetBranch: string,
  extendedResolutions?: Record<string, ExtendedResolutionData>
): MergeReleaseNote {
  const ext = extendedResolutions ?? {};
  const sections: ReleaseNoteSection[] = [];

  // Unchanged sentences
  if (prepared.identical.length > 0) {
    sections.push({
      heading: `Unchanged (${prepared.identical.length})`,
      items: prepared.identical.map((s) => s.text),
    });
  }

  // Modified / resolved conflicts
  const resolved: string[] = [];
  for (let i = 0; i < prepared.similarPairs.length; i++) {
    const pair = prepared.similarPairs[i] as MergeSimilarPair;
    const extRes = ext[String(i)];

    if (extRes?.type === 'both') {
      resolved.push(
        `Kept both: "${truncate(pair.source.text)}" and "${truncate(pair.target.text)}"`
      );
    } else if (pair.resolution === 'source') {
      resolved.push(`Kept source: "${truncate(pair.source.text)}"`);
    } else if (pair.resolution === 'target') {
      resolved.push(`Updated to: "${truncate(pair.target.text)}"`);
    }
  }
  if (resolved.length > 0) {
    sections.push({ heading: `Resolved Changes (${resolved.length})`, items: resolved });
  }

  // Added from source
  const addedFromSource = prepared.onlyInSource.filter((c) => c.keep);
  if (addedFromSource.length > 0) {
    sections.push({
      heading: `Added from ${sourceBranch} (${addedFromSource.length})`,
      items: addedFromSource.map((c) => c.sentence.text),
    });
  }

  // Added from target
  const addedFromTarget = prepared.onlyInTarget.filter((c) => c.keep);
  if (addedFromTarget.length > 0) {
    sections.push({
      heading: `Added from ${targetBranch} (${addedFromTarget.length})`,
      items: addedFromTarget.map((c) => c.sentence.text),
    });
  }

  // Removed
  const removedSource = prepared.onlyInSource.filter((c) => !c.keep);
  const removedTarget = prepared.onlyInTarget.filter((c) => !c.keep);
  const removed = [...removedSource, ...removedTarget];
  if (removed.length > 0) {
    sections.push({
      heading: `Removed (${removed.length})`,
      items: removed.map((c) => c.sentence.text),
    });
  }

  return {
    title: `Merge: ${sourceBranch} → ${targetBranch}`,
    timestamp: new Date().toISOString(),
    sourceBranch,
    targetBranch,
    summary: summary.highlight,
    sections,
  };
}

// ============================================================================
// Markdown Formatter
// ============================================================================

/**
 * Format a release note as Markdown text.
 */
export function formatReleaseNoteAsMarkdown(note: MergeReleaseNote): string {
  const lines: string[] = [];

  lines.push(`# ${note.title}`);
  lines.push('');
  lines.push(`**Date:** ${new Date(note.timestamp).toLocaleString()}`);
  lines.push(`**Summary:** ${note.summary}`);
  lines.push('');

  for (const section of note.sections) {
    lines.push(`## ${section.heading}`);
    lines.push('');
    for (const item of section.items) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by T3X*');

  return lines.join('\n');
}

// ============================================================================
// Helpers
// ============================================================================

function truncate(text: string, max = 80): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}...`;
}
