/**
 * Merge Release Note Generator — Pure Function
 *
 * Transforms merge result + resolutions into a structured release note
 * with human-readable sections (added/updated/removed/conflicts).
 */

import type { MergeResult } from '@t3x-dev/core';
import type { MergeSummary } from '@/components/merge/mergeSummary';
import { truncate } from '@/domain/format/truncate';
import type { ExtendedResolutionData } from '@/store/mergeWorkspaceStore';

// ============================================================================
// Types
// ============================================================================

export interface ReleaseNoteSection {
  heading: string;
  items: string[];
}

export interface MergeReleaseNote {
  title: string;
  timestamp: string;
  sourceBranch: string;
  targetBranch: string;
  summary: string;
  sections: ReleaseNoteSection[];
}

// ============================================================================
// Main Function
// ============================================================================

/**
 * Generate a structured release note from merge data.
 *
 * @param prepared - The MergeResult from prepareMerge()
 * @param summary - Pre-computed merge summary
 * @param sourceBranch - Source branch name
 * @param targetBranch - Target branch name
 * @param conflictResolutions - Map of conflict path → resolution
 * @param keepSource - Set of source-only paths to keep
 * @param keepTarget - Set of target-only paths to keep
 * @param extendedResolutions - Optional extended resolutions (e.g. 'both')
 */
export function generateMergeReleaseNote(
  prepared: MergeResult,
  summary: MergeSummary,
  sourceBranch: string,
  targetBranch: string,
  conflictResolutions?: Record<string, 'source' | 'target'>,
  keepSource?: Set<string>,
  keepTarget?: Set<string>,
  extendedResolutions?: Record<string, ExtendedResolutionData>
): MergeReleaseNote {
  const ext = extendedResolutions ?? {};
  const resolutions = conflictResolutions ?? {};
  const sections: ReleaseNoteSection[] = [];

  // Auto-kept (unchanged) nodes
  if (prepared.autoKept.length > 0) {
    sections.push({
      heading: `Unchanged (${prepared.autoKept.length})`,
      items: prepared.autoKept.map((path) => path),
    });
  }

  // Resolved conflicts
  const resolved: string[] = [];
  for (let i = 0; i < prepared.conflicts.length; i++) {
    const conflict = prepared.conflicts[i];
    const extRes = ext[String(i)];

    if (extRes?.type === 'both') {
      resolved.push(`Kept both versions: "${truncate(conflict.path)}"`);
    } else if (resolutions[conflict.path] === 'source') {
      resolved.push(`Kept source: "${truncate(conflict.path)}"`);
    } else if (resolutions[conflict.path] === 'target') {
      resolved.push(`Updated to target: "${truncate(conflict.path)}"`);
    }
  }
  if (resolved.length > 0) {
    sections.push({ heading: `Resolved Changes (${resolved.length})`, items: resolved });
  }

  // Added from source
  const addedFromSource = keepSource
    ? prepared.onlyInSource.filter((p) => keepSource.has(p))
    : prepared.onlyInSource;
  if (addedFromSource.length > 0) {
    sections.push({
      heading: `Added from ${sourceBranch} (${addedFromSource.length})`,
      items: addedFromSource,
    });
  }

  // Added from target
  const addedFromTarget = keepTarget
    ? prepared.onlyInTarget.filter((p) => keepTarget.has(p))
    : prepared.onlyInTarget;
  if (addedFromTarget.length > 0) {
    sections.push({
      heading: `Added from ${targetBranch} (${addedFromTarget.length})`,
      items: addedFromTarget,
    });
  }

  // Removed
  const removedSource = keepSource ? prepared.onlyInSource.filter((p) => !keepSource.has(p)) : [];
  const removedTarget = keepTarget ? prepared.onlyInTarget.filter((p) => !keepTarget.has(p)) : [];
  const removed = [...removedSource, ...removedTarget];
  if (removed.length > 0) {
    sections.push({
      heading: `Removed (${removed.length})`,
      items: removed,
    });
  }

  return {
    title: `Merge: ${sourceBranch} → ${targetBranch}`,
    timestamp: new Date().toISOString(),
    sourceBranch,
    targetBranch,
    summary: summary.highlight,
    sections,
  };
}

// ============================================================================
// Markdown Formatter
// ============================================================================

/**
 * Format a release note as Markdown text.
 */
export function formatReleaseNoteAsMarkdown(note: MergeReleaseNote): string {
  const lines: string[] = [];

  lines.push(`# ${note.title}`);
  lines.push('');
  lines.push(`**Date:** ${new Date(note.timestamp).toLocaleString()}`);
  lines.push(`**Summary:** ${note.summary}`);
  lines.push('');

  for (const section of note.sections) {
    lines.push(`## ${section.heading}`);
    lines.push('');
    for (const item of section.items) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by T3X*');

  return lines.join('\n');
}
